package it.polimi.model;

public enum State {
    
    LOBBY,SETUP,PLAYERSETUP,SPAWNPLAYER,STARTTURN,USEPOWERUP,RUN,GRAB,SHOOT,ENDACTION,RECHARGE,PASSTURN,DEADPLAYER,SCORINGPLAYERBOARD,RESPWANPLAYER,ENDTURN,FINALSCORING,CHECKILLSHOOT
}
