package it.polimi.model;

public enum State {
    
    SETUP,PLAYERSETUP,SPAWNNPLAYER,STARTTURN,POWERUP,ACTION1,ACTION2,ENDACTION,RECHARGE,PASSTURN,DEADPLAYER,PLAYERBOARDSCORING,RESPWANPALYER,ENDTURN,FINALSCORING,
}
