package it.polimi.model;

public enum State {
    
    LOBBY,SETUP,PLAYERSETUP,SPAWNPLAYER,STARTTURN,CHOSE,USEPOWERUP,RUN,SELECTRUN,GRAB,SELECTGRAB,SELECTSHOOT,SHOOT,ENDACTION,RECHARGE,PASSTURN,DEADPLAYER,SCORINGPLAYERBOARD,RESPWANPLAYER,ENDTURN,FINALSCORING,CHECKILLSHOOT,ERROR,SELECTWEAPON
}
